variables:
  EXTRA_DNF_REPOS: |
                   [KiranBase2.4]
                   name=KiranBase2.4
                   gpgcheck=0
                   baseurl=http://192.168.120.71/kojifiles/repos/KY3.5-1-Kiran-base-2.4-build/latest/x86_64/
  RPM_BUILD_REQUIRES: 'gcc-c++ cmake glib2-devel upower-devel zeromq-devel libnotify-devel pam-devel cryptopp-devel qt5-qtbase-devel qt5-qtx11extras-devel qt5-qtsvg-devel qt5-qtmultimedia-devel qt5-linguist kf5-networkmanager-qt-devel kiran-log-qt5-devel kiran-widgets-qt5-devel kiran-qt5-integration-devel kiran-qdbusxml2cpp kiran-cc-daemon-devel'

include:
  - project: 'os/gitlab-ci'
    ref: main
    file: '/cmake/cxx.gitlab-ci.yml'
